[project]
name = "{{ cookiecutter.package_name }}"
version = "{{ cookiecutter.version }}"
description = "{{ cookiecutter.project_desc }}"
authors = [
    {name = "{{ cookiecutter.author_name }}", email = "{{ cookiecutter.author_email }}"},
]
dependencies = [
    "numpy>=1.26.4",
    "dill>=0.3.8",
    "more-itertools>=10.2.0",
    "ujson>=5.9.0",
    "pydantic[email]>=2.6.1",
    "pydantic-extra-types>=2.5.0",
    "fsspec>=2024.2.0",
    "cython>=3.0.8",
    "python-dateutil>=2.8.2",
]
requires-python = "{{ cookiecutter.python_version }}"
readme = "README.md"
license = {text = "{{ cookiecutter.license }}"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
nvim = [
    "pynvim>=0.5.0",
]
test = [
    "pytest>=8.0.0",
    "pytest-xdist>=3.5.0",
    "pytest-randomly>=3.15.0",
    "pytest-cov>=4.1.0",
    "pytest-beartype>=0.0.2",
    "hypothesis[cli,codemods,dpcontracts,lark,pytz,dateutil,numpy,array_api]>=6.98.4",
]
dev = [
    "mypy>=1.8.0",
    "pylint>=3.0.3",
    "pyright>=1.1.350",
    "jedi-language-server>=0.41.2",
    "black>=24.2.0",
    "bandit>=1.7.7",
    "reorder-python-imports>=3.12.0",
    "flakehell>=0.9.0",
    "mypy-extensions>=1.0.0",
    "pysnooper>=1.2.0",
    "icecream>=2.1.3",
    "beartype>=0.17.2",
]
type = [
    "types-ujson>=5.9.0.0",
]

[tool.pylint]
jobs = 0
extension-pkg-allow-list = ["ujson", "pydantic"]

[tool.pylint.FORMAT]
max-line-length = 140

[tool.pylint."MESSAGE CONTROL"]
disable = [
  "missing-function-docstring",
  "missing-module-docstring",
  "missing-class-docstring",
  "invalid-name",
  "too-few-public-methods",
  "line-too-long",
  "import-outside-toplevel",
  "wrong-import-position",
  "ungrouped-imports",
  "too-many-arguments",
  "too-many-instance-attributes",
  "too-many-branches",
  "too-many-statements",
  "too-many-locals",
  "too-many-return-statements",
  "too-many-nested-blocks",
  "too-many-boolean-expressions",
]

[tool.black]
line-length = 140
target-version = ["py312"]

[tool.mypy]
python_version = "3.12"
plugins = ["numpy.typing.mypy_plugin", "pydantic.mypy"]

follow_imports = "normal"
ignore_missing_imports = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true
disallow_untyped_defs = false # for strict mypy: (this is the tricky one :-))

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true

[tool.pyright]
typeCheckingMode = "strict"
reportMissingModuleSource = "none"
reportMissingImports = "none"
reportMissingTypeStubs = "none"
reportMissingParameterType = "none"
reportUnknownArgumentType = "none"
reportUnknownVariableType = "none"
reportUnknownMemberType = "none"
reportUnknownParameterType = "none"
reportUnknownLambdaType = "none"
reportGeneralTypeIssues = "none"
reportUnusedExpression = "none"
reportConstantRedefinition = "none"
reportUntypedFunctionDecorator = "none"

[tool.flakehell]
max_line_length = 140
show_source = true
format = "grouped"

[tool.flakehell.plugins]
pycodestyle = ["+*"]
pyflakes = ["+*"]

[tool.bandit]
exclude_dirs = ["tests"]
skips = ["B403", "B301", "B101"]
